### list developers
GET http://localhost:3000/developers

### get developer
GET http://localhost:3000/developers/dev_3M-qmbQmTLp51Y_TuWl_Z

### create developer
POST http://localhost:3000/developers
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john-doe@acme.com",
    "dateOfBirth": "1985-01-01"
}

### update developer
PATCH http://localhost:3000/developers/dev_jXwg2UXmyAeDIOsfPeouM
Content-Type: application/json

{
  "email": "teste@acme.com"
}

### delete developer
DELETE http://localhost:3000/developers/dev_3M-qmbQmTLp51Y_TuWl_Z